### 지출 등록
POST http://localhost:8080/api/expenditure
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "categoryId" : 2,
  "amount" : 1000,
  "spentAt" : "2026-11-25 15:12:30",
  "memo" : "테스트"
}

### 지출 삭제
DELETE http://localhost:8080/api/expenditure/1
Authorization: Bearer {{accessToken}}

### 지출 수정
PATCH http://localhost:8080/api/expenditure/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "categoryId" : 1,
  "amount" : 2000,
  "spentAt" : "2026-10-25 15:12:30",
  "memo" : "테스트 중",
  "excludedFromTotal": true
}

### 지출 상세 조회
GET http://localhost:8080/api/expenditure/1
Authorization: Bearer {{accessToken}}


### 지출 목록 조회
GET http://localhost:8080/api/expenditure/list?categoryId=1&startDate=2024-11-26T00:00:00&endDate=2025-11-25T00:00:00&minAmount=1000&maxAmount=10000
Authorization: Bearer {{accessToken}}